### ISSUE TITLE
Make a dashboard of the 3 key Key metrics: new users acquired, DAU, and retained users

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-installer-android#130]
Not necessarily a dashboard per se, but now that we have a way to exclude internal users from such reports (#128) it would be useful to have some bookmarks for appropriately-configured charts.

**Comment by wjt** [comment]
As an aside, for ISTE we added relevant Google Analytics tags to https://www.endlessos.org/conference that identify these users as coming from ISTE 2023 (and the same for the Microsoft store).

**Comment by dbnicholson** [comment]
I think the [Firebase overview](https://analytics.google.com/analytics/web/?authuser=1#/p377000280/reports/dashboard?r=firebase-overview) has most of what you want.

* The Users graph can be switched to New Users.You can also use the [User Acquisition report](https://analytics.google.com/analytics/web/?authuser=1#/p377000280/reports/explorer?r=lifecycle-user-acquisition-v2).
* The first chart on the Firebase overview is User activity over time which shows daily, weekly and monthly users.
* For retention, there's a [Retention overview](https://analytics.google.com/analytics/web/?authuser=1#/p377000280/reports/dashboard?r=lifecycle-retention-overview).

**Comment by dbnicholson** [comment]
I put together a custom report [here](https://analytics.google.com/analytics/web/?authuser=1#/p377000280/reports/dashboard?params=_u..nav%3Dmaui%26_r.5..selmet%3D%5B%22userEngagementDurationPerUser%22%5D&r=5688278195&ruid=91A21D66-65B5-4557-9126-827B66DE0105&collectionId=5688276493). I put this together as a copy of the Firebase report and then added some of the acquisition pieces. Notably, this is an overview report, which means you can just put on pre-assembled cards. That was roughly good enough, but I think if you wanted more customization you'd have to make a detail report and then you're building the actual charts yourself.

You can access that report by going to Reports and then clicking Metrics under the Endless group. Since this seemed like the primary thing we wanted to see, I also set is as the Reports snapshot, which means that when you go to Reports it's what you see.

**Comment by dbnicholson** [comment]
In order to filter out Endless users, I created an [audience](https://analytics.google.com/analytics/web/?authuser=1#/a268839926p377000280/admin/audiences/hub) named "Non Testers". It's all users except those where the install referrer `utm_campaign` value is `test`. In order to use the audience, go to any report and click on the Edit comparisons button. Then click on All Users and change Dimension Value to Non Testers. A shortcut for this is to click on the All Users pill at the top.

So, that works, although I wish it was the default. Interestingly, I also found an Internal Traffic [data filter](https://analytics.google.com/analytics/web/?authuser=1#/a268839926p377000280/admin/datapolicies/datafilters) which would do just that by excluding all events that have the `traffic_type` parameter set to `internal`. Unfortunately, the [help](https://support.google.com/analytics/answer/10104470) says that it only works for websites and you can't use it for apps. I believe the way it works is that you add that tag to events, but in app mode there doesn't appear to be ways to tag events.

Now the bad news. The Non Testers audience only excludes 2 users. I'm pretty sure those are both me. So, I don't think anyone is actually using the [internal install link](https://play.google.com/store/apps/details?id=org.endlessos.Key&referrer=utm_source%3Deos%26utm_campaign%3Dtest).

**Comment by wjt** [comment]
Thanks for this dashboard!

I agree that something seems fishy with this data. I'll open a separate task to follow up on why so few people are being considered Testers.

**Comment by wjt** [comment]
I think I'm right in saying that the dashboard is not filtered by default?

**Comment by wjt** [comment]
For that follow-up I filed:

- https://github.com/endlessm/kolibri-installer-android/issues/158
