### ISSUE TITLE
Detect too-old WebView versions and direct the user to explicitly update it via the Play Store

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-installer-android#160]
See https://github.com/endlessm/kolibri-installer-android/pull/157#issuecomment-1621829305 for one recent example, but this is a recurring problem: particularly on a freshly powerwashed Chromebook, it is normal for the Android System WebView package to be super-old, and this leads to weird bugs because we (reasonably enough) don't test on really old Chromium engine versions. For instance at BETT I hit a problem not because the app was using too-new JS syntax, but because it was using a too-new web platform API.

We should choose a minimum WebView version, then in our app, detect when it is out-of-date and, if so, give the user a deep-link into the Play Store to update it. (Is there even an Intent we could send to the Play Store to update it?)

We should *not* base this on the age of the WebView relative to today's date. Consider this case:

- Student installs Endless Key, downloads a load of content
- Student goes home for the summer, has no internet at home
- Time passes
- Suddenly the WebView (which has not been updated due to being offline) becomes "too old" and the student is locked out of their perfectly-good Endless Key

**Comment by dbnicholson** [comment]
The way to detect the system webview in use appears to be the [`Webview.getCurrentWebViewPackage`](https://developer.android.com/reference/android/webkit/WebView#getCurrentWebViewPackage()) method. This returns a `PackageInfo` from which you can get [`versionName`](https://developer.android.com/reference/android/content/pm/PackageInfo#versionName). In the Android app, the webview can be accessed from python using `kolibri_android.android_utils.get_activity().getMainWebView()`.

One thing we need to be prepared for is that there can be different system webviews. Typically on a Chromebook this is going to be `com.google.android.webview`. On my barebones emulator without Google integration, it's `com.android.webview`. I've also seen in other contexts that, for example, Samsung ships its own webview component. All that to say that we should likely only match `com.google.android.webview` since that's the versioning scheme we understand here.

**Comment by dbnicholson** [comment]
To actually get the user to update, I think the best we can do is open it in the Play Store via an `Intent` as described [here](https://stackoverflow.com/a/11753070). Once the webview is updated, then I think we'd have to restart the app to use it. I believe to restart an activity you can call the [`recreate`](https://developer.android.com/reference/android/app/Activity#recreate()) method.

**Comment by dbnicholson** [comment]
I missed this from the [getCurrentWebViewPackage](https://developer.android.com/reference/android/webkit/WebView#getCurrentWebViewPackage()) docs:

> If the WebView package changes, any app process that has loaded WebView will be killed.

So, I guess we don't have to worry about restarting the app if the user follows through on the update since it's going to be killed as soon as that happens.

I don't know what the desired flow is. Maybe - bring up a dialog warning about the outdated webview and instructing them to update the webview. The button would say Update and open the Play Store. Possibly you could have another Ignore button that just carries on. And a preference that stores whether it was ignored. I'm just a bit worried about systems where they can't update the webview and we have an annoying popup every time the app launches.

**Comment by wjt** [comment]
My fear is that if we have an *Ignore* button people will just ignore it. So long as we don't increase the minimum webview version, if the app works once it will work again in future. And we *know* that the app does not work with certain old webviews – so systems running such a webview which can't update the webview can't use the app at all…

**Comment by dbnicholson** [comment]
So what do you think the process should be?

**Comment by wjt** [comment]
My initial idea was as you describe:

> Bring up a dialog warning about the outdated webview and instructing them to update the webview. The button would say Update and open the Play Store.

I guess I see the argument for an Ignore button because a false-positive would render the app unusable. I don't think it is necessary to persist the ignore state though.

I had a quick look at the Material design component documentation, looking for an equivalent to the [Banner](https://developer.gnome.org/hig/patterns/feedback/banners.html) pattern from  GNOME, wondering if there is a suitable pattern to show a warning that does not prevent the app being used but which can't be dismissed without updating the webview.

The guidelines for when to use a [Snackbar](https://m3.material.io/components/snackbar/guidelines) compared to a Dialog allude to the existence of a Banner but the current version of Material doesn't seem to have one. Maybe a simple dialog on first launch is sufficient.

@jofilizola What do you think?

**Comment by erikos** [comment]
We should be able to verify this in **Ladybird 6.31-379** as https://github.com/endlessm/kolibri-installer-android/commit/4bab8c8c92c0ba1b6ce9b748a2845b92407f9153 has been pulled in https://ci.endlessos.org/job/kolibri-installer-android/210/

**Comment by erikos** [comment]
I would like to make sure that we actually verify this.

**Comment by pwithnall** [comment]
I’ve just re-tested on my Chromebook using the [apk linked above](https://ci.endlessos.org/job/kolibri-installer-android/210/), and on running Endless Key, I successfully get a dialogue saying “You need to update the Android System Webview component to use Endless Key”. The update button opens the Play store on the right page.

I haven’t updated my webview yet, in case we want to do further testing for the rest of https://github.com/endlessm/kolibri-installer-android/issues/159

**Comment by vanessa-chang** [comment]
The minimum webview package for my chromebook is 88.0.4324.181. I was not able to get the prompt dialogue. (app version: 6.32-380. I guess my webview it's not too-old. :)

**Comment by erikos** [comment]
> The minimum webview package for my chromebook is 88.0.4324.181. I was not able to get the prompt dialogue. (app version: 6.32-380. I guess my webview it's not too-old. :)

Yes, the version has to be below 80. Philip was testing with his ancient Webview 68.0.3440.91

**Comment by wjt** [comment]
Then, I think this is verified. The dialog is shown when necessary, and not when not.
