### ISSUE TITLE
Key on Android: select Spanish content pack based on locale

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-installer-android#187]
Follow up of Select Spanish content pack based on locale #786

In the Flatpak this is working fine. On the Chromebook this is not working yet. The app still shows an English UI even though the system locale is set to Spanish.

(was https://github.com/endlessm/kolibri-explore-plugin/issues/857)

Comment from Manuel: https://github.com/endlessm/kolibri-explore-plugin/issues/857#issuecomment-1737293293

**Comment by dbnicholson** [comment]
As @manuq pointed out, the automatic provision file currently sets the language [to English](https://github.com/endlessm/kolibri-installer-android/blob/601a04d408ebb6595b4d47aafc11bfffaf31bba5/src/automatic_provision.json#L13). However, in the flatpak the language [is unset](https://github.com/endlessm/endless-key-flatpak/blob/f2eae745ca088e4b4abf88e94ae1bc3ae8fdd12d/src/kolibri_daemon/kolibri_utils.py#L137) to use the system language. @dylanmccall's fix to allow `language_id` to [just be left out](https://github.com/learningequality/kolibri/issues/11248) was included in kolibri 0.16.0-beta6.

This probably affects the Windows build, too.

**Comment by dbnicholson** [comment]
Hmm, I think this is going to need a migration to remove the language ID from the device settings. We should probably remove the awful hardcoded `admin:admin` superuser while there since it's a glaring security hole.

**Comment by dylanmccall** [comment]
> @dylanmccall's fix to allow `language_id` to [just be left out](https://github.com/learningequality/kolibri/issues/11248) was included in kolibri 0.16.0-beta6.

Just to clarify, it can't be left out. Must be `null` or `""`. Leaving it out leads to the default behaviour, which is to set the default language to whatever the language is at setup time (as opposed to using the accepts-language header from each request). But yes, should be a quick fix at this point ;)

That's a good thought about a migration. I think it's probably fine since our existing users probably only expect English anyway, but it wouldn't hurt. Alas, I guess we'd need to do that in the app code. Or can a migration in a plugin like kolibri-expore-plugin evilly touch other models? I wish we had a separate plugin in which to put that kind of Endless Key-specific thing inside Kolibri, but as long as we remember to remove it in the future.

**Comment by dbnicholson** [comment]
> > @dylanmccall's fix to allow `language_id` to [just be left out](https://github.com/learningequality/kolibri/issues/11248) was included in kolibri 0.16.0-beta6.
> 
> Just to clarify, it can't be left out. Must be `null` or `""`. Leaving it out leads to the default behaviour, which is to set the default language to whatever the language is at setup time (as opposed to using the accepts-language header from each request). But yes, should be a quick fix at this point ;)

Right, I just reread the issue/PR.

> That's a good thought about a migration. I think it's probably fine since our existing users probably only expect English anyway, but it wouldn't hurt. Alas, I guess we'd need to do that in the app code. Or can a migration in a plugin like kolibri-expore-plugin evilly touch other models? I wish we had a separate plugin in which to put that kind of Endless Key-specific thing inside Kolibri, but as long as we remember to remove it in the future.

I think we'd want a plugin in the app code. But that's not so bad. At least for Android we'd eventually want that anyways to bridge from Kolibri tasks to WorkManager tasks. That's what LE is already doing.

**Comment by dbnicholson** [comment]
I tested #188 in an Android emulator and it DTRT.

One bad part is that the Android webview that I have exactly passes through the system language settings. Unlike Chrome on my system where it has automatically set `navigator.language` (and the `Accept-Language` header) to `['en-US', 'en']`, Android webview initially just had `['en-US']`, then exactly `es-GT` or `es-ES` when I set those as the system language. Of note is that it didn't build up a fallback list like `['es-GT', 'es-419', 'es']` like we saw on Chrome.

**Comment by dylanmccall** [comment]
https://github.com/endlessm/kolibri-installer-android/issues/187

> I tested #188 in an Android emulator and it DTRT.
> 
> One bad part is that the Android webview that I have exactly passes through the system language settings. Unlike Chrome on my system where it has automatically set `navigator.language` (and the `Accept-Language` header) to `['en-US', 'en']`, Android webview initially just had `['en-US']`, then exactly `es-GT` or `es-ES` when I set those as the system language. Of note is that it didn't build up a fallback list like `['es-GT', 'es-419', 'es']` like we saw on Chrome.

I played with this for a while. Looking at https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages, it seems like `navigator.language` _should be_ the same as `Accept-Language`, but of course [_everything is wrong on the internet_](https://xkcd.com/386/). This is the case for Firefox and Chrome on the desktop, as well as native Chrome on my Chromebook. I can navigate to http://example.com, open a web inspector, and compare the request headers and the navigator.language property, and they match.

But it is _not_ the case for Chrome on Android. In an Android emulator, I set up my system language so that US Spanish is a fallback from US English. If I navigate to http://example.com, here is that request header:

```
Accept-Language: en-US,en;q=0.9,es-US;q=0.8,es;q=0.7
```

And here is what I get in the JavaScript console:

```
navigator.languages: ['en-US']
```

It is the same behaviour in an Android WebView, such as in the Endless Key app.

(And it is the same behaviour in both GNOME Web and WebKitGTK with the Endless Key, _and_ my iPhone. Which makes me think maybe we have a bone to pick with WebKit, but also Chrome, but only Chrome on Android?).

So, that's pretty bizarre. But the good news is I think the request header is trustworthy through all of it, so we can probably work around this. It looks like Kolibri sorts this all out on the server, and I guess now we know one reason why.

**Comment by manuq** [comment]
Great findings, @dylanmccall!

> It looks like Kolibri sorts this all out on the server, and I guess now we know one reason why.

That leaves us either adding a language selector like Kolibri. Or passing the system language to the web engine, which unfortunately will be different in each app (Windows, Android, flatpak).

**Comment by dbnicholson** [comment]
Another interesting effect of the language handling is that even though the plugin contents were translated, the loading screen was not because it doesn't do any locale heuristics and the only Spanish translation is `es-419`. That will need some followup on the explore plugin side.

While that's all very interesting about the language debugging, we still need to not hardcode the language as `en` during provisioning. Can someone review #188?

**Comment by erikos** [comment]
Now that https://github.com/endlessm/kolibri-installer-android/pull/188 has been merged it would be great to get a new build in internal testing, I think the builds have not been uploaded https://ci.endlessos.org/job/kolibri-installer-android/ 

Kicked-off https://ci.endlessos.org/job/kolibri-installer-android-upload/114/

**Comment by manuq** [comment]
@erikos keep in mind that the PR probably won't make an ES system display the app in Spanish as per the tech details above.

**Comment by dbnicholson** [comment]
This can be tested in release 414.

**Comment by vanessa-chang** [comment]
Verified passed in Chromebook version: Narwhal 7.8-415.
